name: Trigger React Kanban Board Test Runner

on:
  pull_request_target:
    branches: ["main"]

jobs:
  react_kanban_board_test_runner:
    uses: developer-job-simulation/react-kanban-board-tests/.github/workflows/main.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }} 
